# Generated by Django 5.1.1 on 2024-09-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_products_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='register',
            name='district',
        ),
        migrations.RemoveField(
            model_name='register',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='register',
            name='pan',
        ),
    ]
